### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by Pato546** [nyggus/makepackage#11]
I want to contribute to your package but I can see any CONTRIBUTING file, so I'm kinda wondering how I should go about it.

**Comment by nyggus** [comment]
Great, everyone is welcome to contribute! I did not include the CONTRIBUTING file, but you will find a dedicated section in README: https://github.com/nyggus/makepackage#contribution

**Comment by Pato546** [comment]
Okay thanks, probably I should have read the README first.
