### ISSUE TITLE
Typo in mypackage/mypackage.py

### ISSUE THREAD

**Issue by AlixBernard** [nyggus/makepackage#5]
There is a small mistake in the file mypackage/mypackage.py.
On line 62:
```python
def make_dirs(root_path: pathlib.Path, package_name: str) -> None:
```
While `pathlib.Path` should be replaced by `Path`:
```python
def make_dirs(root_path: Path, package_name: str) -> None:
```
Once this correction is done the package seems to work as intended.

**Comment by nyggus** [comment]
Hi,

Thanks for your interest in the package. Indeed, thanks for spotting the
typo! Would you like to make the change and create a pull request? I can of
course do it myself, but if you want to contribute, even if with this is
just a small change, then you will be welcomed.

Best wishes,
Marcin

czw., 11 sie 2022, 06:04 użytkownik AlixBernard ***@***.***>
napisał:

**Comment by nyggus** [comment]
Thanks a lot. Approved, merged. I forgot to increment the version, so I did
it after, to version 0.1.3. I hope you will enjoy using the package 😀.

Best wishes,
Marcin


czw., 11 sie 2022 o 07:43 Marcin Kozak ***@***.***> napisał(a):
