### ISSUE TITLE
installing from source - README not found

### ISSUE THREAD

**Issue by hp0404** [nyggus/makepackage#7]
I tried installing `makepackage` from source calling setup.py from *a parent directory* like so:
```console
python makepackage/setup.py develop
```
It raised an error:
```console
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```
This could be easily fixed with pathlib: 
```python
import setuptools
from pathlib import Path

ROOT = Path(__file__).resolve().parent


with open(ROOT / "README.md", "r") as fh:
    long_description = fh.read()

...
```

**Comment by nyggus** [comment]
I always install from the root directory, not from parent directory, as this seems to me a natural thing to do. The parent directory does not seem to me a good place to do things with the package. But this change will not break anything, and will enable one to install the package from the parent directory, so I am fine with it — at least no one else will again get this error. So, let's do it.

**Comment by nyggus** [comment]
Hello! Thanks for the issue and spotting the problem. I replied in github,
but I wanted also to reply through email. Would you like to make the change
or would you like me to do it? I am fine with both approaches, but I am
happy to see you among the collaborators. Please let me know.

Thanks and best wishes,
Marcin

czw., 11 sie 2022, 21:52 użytkownik hp0404 ***@***.***>
napisał:
